baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = ""
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[params]
address = ""
author = "Aleksandr Cheverdak"
copyright = "Copyrighht &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"
description = ""
email = "a-cheverdak@ya.ru"
google_analitycs_id = "Your ID"
home = "Home"
logo = ""
phone = ""
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/aleksandr-cheverdak/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://www.facebook.com/evrohachik"
icon = "ti-facebook"
[[params.social]]
URL = "https://www.instagram.com/evrohachik/"
icon = "ti-instagram"
[[params.social]]
URL = "https://twitter.com/evrohachik2"
icon = "ti-twitter-alt"
